import React from 'react';
import { render } from '@testing-library/react';
import "@testing-library/jest-dom"
import RootLayout, { metadata } from './layout';

describe('RootLayout', () => {
  it('renders children correctly', () => {
    const { getByText } = render(
      <RootLayout>
        <div>Test Child</div>
      </RootLayout>
    );
    expect(getByText('Test Child')).toBeInTheDocument();
  });

  it('sets the correct metadata', () => {
    expect(metadata.title).toBe('Next.js');
    expect(metadata.description).toBe('Generated by Next.js');
  });
});