name: Deploy swinburne-dev nextjs AWS

on:
    push:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Read .nvmrc
              run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
              id: nvm

            - name: Set up Node.js version ${{ steps.nvm.outputs.NODE_VERSION }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

            - name: Run npm install, build, and export
              run: |
                  npm install
                  npx nx run swinburne-dev:build
            - uses: aws-actions/configure-aws-credentials@v1
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: eu-west-2
