name: Deploy swinburne-dev nextjs AWS

on:
    push:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Read .nvmrc
              run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
              id: nvm

            - name: Set up Node.js version ${{ steps.nvm.outputs.NODE_VERSION }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

            - name: Run npm install, build, and export
              run: |
                  npm install
                  npx nx run swinburne-dev:export
